name: 'heart_disease_522'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.3.1
  - pandas=2.2.2
  - ipykernel=6.29.5
  - nb_conda_kernels=2.5.1
  - scipy=1.14.1
  - matplotlib=3.9.3
  - scikit-learn=1.5.2
  - requests=2.32.3
  - seaborn=0.13.2
  - ucimlrepo=0.0.7
  - pandera=0.20.2
  - quarto=1.5.57
  - click=8.1.7
  - tabulate=0.9.0
  - pip:
      - deepchecks==0.18.1
